/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedVehiclesIndexRouteImport } from './routes/_protected/vehicles/index'
import { Route as ProtectedVehicleTypesIndexRouteImport } from './routes/_protected/vehicle-types/index'
import { Route as ProtectedUsersIndexRouteImport } from './routes/_protected/users/index'
import { Route as ProtectedUserSettingsIndexRouteImport } from './routes/_protected/user-settings/index'
import { Route as ProtectedUserInitialValuesIndexRouteImport } from './routes/_protected/user-initial-values/index'
import { Route as ProtectedSlotsIndexRouteImport } from './routes/_protected/slots/index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings/index'
import { Route as ProtectedSchoolsIndexRouteImport } from './routes/_protected/schools/index'
import { Route as ProtectedRidersIndexRouteImport } from './routes/_protected/riders/index'
import { Route as ProtectedReportsIndexRouteImport } from './routes/_protected/reports/index'
import { Route as ProtectedProfileIndexRouteImport } from './routes/_protected/profile/index'
import { Route as ProtectedPreferencesIndexRouteImport } from './routes/_protected/preferences/index'
import { Route as ProtectedOrganizationsIndexRouteImport } from './routes/_protected/organizations/index'
import { Route as ProtectedIncomeGroupsIndexRouteImport } from './routes/_protected/income-groups/index'
import { Route as ProtectedFiscalYearsIndexRouteImport } from './routes/_protected/fiscal-years/index'
import { Route as ProtectedFeesIndexRouteImport } from './routes/_protected/fees/index'
import { Route as ProtectedFeeHeadsIndexRouteImport } from './routes/_protected/fee-heads/index'
import { Route as ProtectedExpensesIndexRouteImport } from './routes/_protected/expenses/index'
import { Route as ProtectedExpenseHeadsIndexRouteImport } from './routes/_protected/expense-heads/index'
import { Route as ProtectedExpenseGroupsIndexRouteImport } from './routes/_protected/expense-groups/index'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedCreditNotesIndexRouteImport } from './routes/_protected/credit-notes/index'
import { Route as GuestLoginIndexRouteImport } from './routes/_guest/login/index'
import { Route as ProtectedReportsVehicleFeeCollectionRouteImport } from './routes/_protected/reports/vehicle-fee-collection'
import { Route as ProtectedReportsSchoolFeeCollectionRouteImport } from './routes/_protected/reports/school-fee-collection'
import { Route as ProtectedReportsRiderFeeCollectionRouteImport } from './routes/_protected/reports/rider-fee-collection'
import { Route as ProtectedReportsPendingCollectionRouteImport } from './routes/_protected/reports/pending-collection'
import { Route as ProtectedReportsMonthlyTrendRouteImport } from './routes/_protected/reports/monthly-trend'
import { Route as ProtectedReportsIncomeExpenseRouteImport } from './routes/_protected/reports/income-expense'
import { Route as ProtectedReportsDailyCollectionRouteImport } from './routes/_protected/reports/daily-collection'
import { Route as ProtectedReportsCreditNotesRouteImport } from './routes/_protected/reports/credit-notes'
import { Route as ProtectedFeesNewRouteImport } from './routes/_protected/fees/new'
import { Route as ProtectedExpensesNewRouteImport } from './routes/_protected/expenses/new'
import { Route as ProtectedFeesFeeIdEditRouteImport } from './routes/_protected/fees/$feeId.edit'
import { Route as ProtectedExpensesExpenseIdEditRouteImport } from './routes/_protected/expenses/$expenseId.edit'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVehiclesIndexRoute = ProtectedVehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedVehicleTypesIndexRoute =
  ProtectedVehicleTypesIndexRouteImport.update({
    id: '/vehicle-types/',
    path: '/vehicle-types/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedUsersIndexRoute = ProtectedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedUserSettingsIndexRoute =
  ProtectedUserSettingsIndexRouteImport.update({
    id: '/user-settings/',
    path: '/user-settings/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedUserInitialValuesIndexRoute =
  ProtectedUserInitialValuesIndexRouteImport.update({
    id: '/user-initial-values/',
    path: '/user-initial-values/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedSlotsIndexRoute = ProtectedSlotsIndexRouteImport.update({
  id: '/slots/',
  path: '/slots/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSchoolsIndexRoute = ProtectedSchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedRidersIndexRoute = ProtectedRidersIndexRouteImport.update({
  id: '/riders/',
  path: '/riders/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedReportsIndexRoute = ProtectedReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedProfileIndexRoute = ProtectedProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPreferencesIndexRoute =
  ProtectedPreferencesIndexRouteImport.update({
    id: '/preferences/',
    path: '/preferences/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedOrganizationsIndexRoute =
  ProtectedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedIncomeGroupsIndexRoute =
  ProtectedIncomeGroupsIndexRouteImport.update({
    id: '/income-groups/',
    path: '/income-groups/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedFiscalYearsIndexRoute =
  ProtectedFiscalYearsIndexRouteImport.update({
    id: '/fiscal-years/',
    path: '/fiscal-years/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedFeesIndexRoute = ProtectedFeesIndexRouteImport.update({
  id: '/fees/',
  path: '/fees/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeeHeadsIndexRoute = ProtectedFeeHeadsIndexRouteImport.update({
  id: '/fee-heads/',
  path: '/fee-heads/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExpensesIndexRoute = ProtectedExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExpenseHeadsIndexRoute =
  ProtectedExpenseHeadsIndexRouteImport.update({
    id: '/expense-heads/',
    path: '/expense-heads/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedExpenseGroupsIndexRoute =
  ProtectedExpenseGroupsIndexRouteImport.update({
    id: '/expense-groups/',
    path: '/expense-groups/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCreditNotesIndexRoute =
  ProtectedCreditNotesIndexRouteImport.update({
    id: '/credit-notes/',
    path: '/credit-notes/',
    getParentRoute: () => ProtectedRoute,
  } as any)
const GuestLoginIndexRoute = GuestLoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => GuestRoute,
} as any)
const ProtectedReportsVehicleFeeCollectionRoute =
  ProtectedReportsVehicleFeeCollectionRouteImport.update({
    id: '/reports/vehicle-fee-collection',
    path: '/reports/vehicle-fee-collection',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsSchoolFeeCollectionRoute =
  ProtectedReportsSchoolFeeCollectionRouteImport.update({
    id: '/reports/school-fee-collection',
    path: '/reports/school-fee-collection',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsRiderFeeCollectionRoute =
  ProtectedReportsRiderFeeCollectionRouteImport.update({
    id: '/reports/rider-fee-collection',
    path: '/reports/rider-fee-collection',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsPendingCollectionRoute =
  ProtectedReportsPendingCollectionRouteImport.update({
    id: '/reports/pending-collection',
    path: '/reports/pending-collection',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsMonthlyTrendRoute =
  ProtectedReportsMonthlyTrendRouteImport.update({
    id: '/reports/monthly-trend',
    path: '/reports/monthly-trend',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsIncomeExpenseRoute =
  ProtectedReportsIncomeExpenseRouteImport.update({
    id: '/reports/income-expense',
    path: '/reports/income-expense',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsDailyCollectionRoute =
  ProtectedReportsDailyCollectionRouteImport.update({
    id: '/reports/daily-collection',
    path: '/reports/daily-collection',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedReportsCreditNotesRoute =
  ProtectedReportsCreditNotesRouteImport.update({
    id: '/reports/credit-notes',
    path: '/reports/credit-notes',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedFeesNewRoute = ProtectedFeesNewRouteImport.update({
  id: '/fees/new',
  path: '/fees/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExpensesNewRoute = ProtectedExpensesNewRouteImport.update({
  id: '/expenses/new',
  path: '/expenses/new',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedFeesFeeIdEditRoute = ProtectedFeesFeeIdEditRouteImport.update({
  id: '/fees/$feeId/edit',
  path: '/fees/$feeId/edit',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedExpensesExpenseIdEditRoute =
  ProtectedExpensesExpenseIdEditRouteImport.update({
    id: '/expenses/$expenseId/edit',
    path: '/expenses/$expenseId/edit',
    getParentRoute: () => ProtectedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/expenses/new': typeof ProtectedExpensesNewRoute
  '/fees/new': typeof ProtectedFeesNewRoute
  '/reports/credit-notes': typeof ProtectedReportsCreditNotesRoute
  '/reports/daily-collection': typeof ProtectedReportsDailyCollectionRoute
  '/reports/income-expense': typeof ProtectedReportsIncomeExpenseRoute
  '/reports/monthly-trend': typeof ProtectedReportsMonthlyTrendRoute
  '/reports/pending-collection': typeof ProtectedReportsPendingCollectionRoute
  '/reports/rider-fee-collection': typeof ProtectedReportsRiderFeeCollectionRoute
  '/reports/school-fee-collection': typeof ProtectedReportsSchoolFeeCollectionRoute
  '/reports/vehicle-fee-collection': typeof ProtectedReportsVehicleFeeCollectionRoute
  '/login/': typeof GuestLoginIndexRoute
  '/credit-notes/': typeof ProtectedCreditNotesIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
  '/expense-groups/': typeof ProtectedExpenseGroupsIndexRoute
  '/expense-heads/': typeof ProtectedExpenseHeadsIndexRoute
  '/expenses/': typeof ProtectedExpensesIndexRoute
  '/fee-heads/': typeof ProtectedFeeHeadsIndexRoute
  '/fees/': typeof ProtectedFeesIndexRoute
  '/fiscal-years/': typeof ProtectedFiscalYearsIndexRoute
  '/income-groups/': typeof ProtectedIncomeGroupsIndexRoute
  '/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/preferences/': typeof ProtectedPreferencesIndexRoute
  '/profile/': typeof ProtectedProfileIndexRoute
  '/reports/': typeof ProtectedReportsIndexRoute
  '/riders/': typeof ProtectedRidersIndexRoute
  '/schools/': typeof ProtectedSchoolsIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/slots/': typeof ProtectedSlotsIndexRoute
  '/user-initial-values/': typeof ProtectedUserInitialValuesIndexRoute
  '/user-settings/': typeof ProtectedUserSettingsIndexRoute
  '/users/': typeof ProtectedUsersIndexRoute
  '/vehicle-types/': typeof ProtectedVehicleTypesIndexRoute
  '/vehicles/': typeof ProtectedVehiclesIndexRoute
  '/expenses/$expenseId/edit': typeof ProtectedExpensesExpenseIdEditRoute
  '/fees/$feeId/edit': typeof ProtectedFeesFeeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof ProtectedIndexRoute
  '/expenses/new': typeof ProtectedExpensesNewRoute
  '/fees/new': typeof ProtectedFeesNewRoute
  '/reports/credit-notes': typeof ProtectedReportsCreditNotesRoute
  '/reports/daily-collection': typeof ProtectedReportsDailyCollectionRoute
  '/reports/income-expense': typeof ProtectedReportsIncomeExpenseRoute
  '/reports/monthly-trend': typeof ProtectedReportsMonthlyTrendRoute
  '/reports/pending-collection': typeof ProtectedReportsPendingCollectionRoute
  '/reports/rider-fee-collection': typeof ProtectedReportsRiderFeeCollectionRoute
  '/reports/school-fee-collection': typeof ProtectedReportsSchoolFeeCollectionRoute
  '/reports/vehicle-fee-collection': typeof ProtectedReportsVehicleFeeCollectionRoute
  '/login': typeof GuestLoginIndexRoute
  '/credit-notes': typeof ProtectedCreditNotesIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
  '/expense-groups': typeof ProtectedExpenseGroupsIndexRoute
  '/expense-heads': typeof ProtectedExpenseHeadsIndexRoute
  '/expenses': typeof ProtectedExpensesIndexRoute
  '/fee-heads': typeof ProtectedFeeHeadsIndexRoute
  '/fees': typeof ProtectedFeesIndexRoute
  '/fiscal-years': typeof ProtectedFiscalYearsIndexRoute
  '/income-groups': typeof ProtectedIncomeGroupsIndexRoute
  '/organizations': typeof ProtectedOrganizationsIndexRoute
  '/preferences': typeof ProtectedPreferencesIndexRoute
  '/profile': typeof ProtectedProfileIndexRoute
  '/reports': typeof ProtectedReportsIndexRoute
  '/riders': typeof ProtectedRidersIndexRoute
  '/schools': typeof ProtectedSchoolsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/slots': typeof ProtectedSlotsIndexRoute
  '/user-initial-values': typeof ProtectedUserInitialValuesIndexRoute
  '/user-settings': typeof ProtectedUserSettingsIndexRoute
  '/users': typeof ProtectedUsersIndexRoute
  '/vehicle-types': typeof ProtectedVehicleTypesIndexRoute
  '/vehicles': typeof ProtectedVehiclesIndexRoute
  '/expenses/$expenseId/edit': typeof ProtectedExpensesExpenseIdEditRoute
  '/fees/$feeId/edit': typeof ProtectedFeesFeeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_guest': typeof GuestRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/expenses/new': typeof ProtectedExpensesNewRoute
  '/_protected/fees/new': typeof ProtectedFeesNewRoute
  '/_protected/reports/credit-notes': typeof ProtectedReportsCreditNotesRoute
  '/_protected/reports/daily-collection': typeof ProtectedReportsDailyCollectionRoute
  '/_protected/reports/income-expense': typeof ProtectedReportsIncomeExpenseRoute
  '/_protected/reports/monthly-trend': typeof ProtectedReportsMonthlyTrendRoute
  '/_protected/reports/pending-collection': typeof ProtectedReportsPendingCollectionRoute
  '/_protected/reports/rider-fee-collection': typeof ProtectedReportsRiderFeeCollectionRoute
  '/_protected/reports/school-fee-collection': typeof ProtectedReportsSchoolFeeCollectionRoute
  '/_protected/reports/vehicle-fee-collection': typeof ProtectedReportsVehicleFeeCollectionRoute
  '/_guest/login/': typeof GuestLoginIndexRoute
  '/_protected/credit-notes/': typeof ProtectedCreditNotesIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
  '/_protected/expense-groups/': typeof ProtectedExpenseGroupsIndexRoute
  '/_protected/expense-heads/': typeof ProtectedExpenseHeadsIndexRoute
  '/_protected/expenses/': typeof ProtectedExpensesIndexRoute
  '/_protected/fee-heads/': typeof ProtectedFeeHeadsIndexRoute
  '/_protected/fees/': typeof ProtectedFeesIndexRoute
  '/_protected/fiscal-years/': typeof ProtectedFiscalYearsIndexRoute
  '/_protected/income-groups/': typeof ProtectedIncomeGroupsIndexRoute
  '/_protected/organizations/': typeof ProtectedOrganizationsIndexRoute
  '/_protected/preferences/': typeof ProtectedPreferencesIndexRoute
  '/_protected/profile/': typeof ProtectedProfileIndexRoute
  '/_protected/reports/': typeof ProtectedReportsIndexRoute
  '/_protected/riders/': typeof ProtectedRidersIndexRoute
  '/_protected/schools/': typeof ProtectedSchoolsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/slots/': typeof ProtectedSlotsIndexRoute
  '/_protected/user-initial-values/': typeof ProtectedUserInitialValuesIndexRoute
  '/_protected/user-settings/': typeof ProtectedUserSettingsIndexRoute
  '/_protected/users/': typeof ProtectedUsersIndexRoute
  '/_protected/vehicle-types/': typeof ProtectedVehicleTypesIndexRoute
  '/_protected/vehicles/': typeof ProtectedVehiclesIndexRoute
  '/_protected/expenses/$expenseId/edit': typeof ProtectedExpensesExpenseIdEditRoute
  '/_protected/fees/$feeId/edit': typeof ProtectedFeesFeeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses/new'
    | '/fees/new'
    | '/reports/credit-notes'
    | '/reports/daily-collection'
    | '/reports/income-expense'
    | '/reports/monthly-trend'
    | '/reports/pending-collection'
    | '/reports/rider-fee-collection'
    | '/reports/school-fee-collection'
    | '/reports/vehicle-fee-collection'
    | '/login/'
    | '/credit-notes/'
    | '/dashboard/'
    | '/expense-groups/'
    | '/expense-heads/'
    | '/expenses/'
    | '/fee-heads/'
    | '/fees/'
    | '/fiscal-years/'
    | '/income-groups/'
    | '/organizations/'
    | '/preferences/'
    | '/profile/'
    | '/reports/'
    | '/riders/'
    | '/schools/'
    | '/settings/'
    | '/slots/'
    | '/user-initial-values/'
    | '/user-settings/'
    | '/users/'
    | '/vehicle-types/'
    | '/vehicles/'
    | '/expenses/$expenseId/edit'
    | '/fees/$feeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses/new'
    | '/fees/new'
    | '/reports/credit-notes'
    | '/reports/daily-collection'
    | '/reports/income-expense'
    | '/reports/monthly-trend'
    | '/reports/pending-collection'
    | '/reports/rider-fee-collection'
    | '/reports/school-fee-collection'
    | '/reports/vehicle-fee-collection'
    | '/login'
    | '/credit-notes'
    | '/dashboard'
    | '/expense-groups'
    | '/expense-heads'
    | '/expenses'
    | '/fee-heads'
    | '/fees'
    | '/fiscal-years'
    | '/income-groups'
    | '/organizations'
    | '/preferences'
    | '/profile'
    | '/reports'
    | '/riders'
    | '/schools'
    | '/settings'
    | '/slots'
    | '/user-initial-values'
    | '/user-settings'
    | '/users'
    | '/vehicle-types'
    | '/vehicles'
    | '/expenses/$expenseId/edit'
    | '/fees/$feeId/edit'
  id:
    | '__root__'
    | '/_guest'
    | '/_protected'
    | '/_protected/'
    | '/_protected/expenses/new'
    | '/_protected/fees/new'
    | '/_protected/reports/credit-notes'
    | '/_protected/reports/daily-collection'
    | '/_protected/reports/income-expense'
    | '/_protected/reports/monthly-trend'
    | '/_protected/reports/pending-collection'
    | '/_protected/reports/rider-fee-collection'
    | '/_protected/reports/school-fee-collection'
    | '/_protected/reports/vehicle-fee-collection'
    | '/_guest/login/'
    | '/_protected/credit-notes/'
    | '/_protected/dashboard/'
    | '/_protected/expense-groups/'
    | '/_protected/expense-heads/'
    | '/_protected/expenses/'
    | '/_protected/fee-heads/'
    | '/_protected/fees/'
    | '/_protected/fiscal-years/'
    | '/_protected/income-groups/'
    | '/_protected/organizations/'
    | '/_protected/preferences/'
    | '/_protected/profile/'
    | '/_protected/reports/'
    | '/_protected/riders/'
    | '/_protected/schools/'
    | '/_protected/settings/'
    | '/_protected/slots/'
    | '/_protected/user-initial-values/'
    | '/_protected/user-settings/'
    | '/_protected/users/'
    | '/_protected/vehicle-types/'
    | '/_protected/vehicles/'
    | '/_protected/expenses/$expenseId/edit'
    | '/_protected/fees/$feeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  GuestRoute: typeof GuestRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/vehicles/': {
      id: '/_protected/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof ProtectedVehiclesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/vehicle-types/': {
      id: '/_protected/vehicle-types/'
      path: '/vehicle-types'
      fullPath: '/vehicle-types/'
      preLoaderRoute: typeof ProtectedVehicleTypesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/users/': {
      id: '/_protected/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof ProtectedUsersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/user-settings/': {
      id: '/_protected/user-settings/'
      path: '/user-settings'
      fullPath: '/user-settings/'
      preLoaderRoute: typeof ProtectedUserSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/user-initial-values/': {
      id: '/_protected/user-initial-values/'
      path: '/user-initial-values'
      fullPath: '/user-initial-values/'
      preLoaderRoute: typeof ProtectedUserInitialValuesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/slots/': {
      id: '/_protected/slots/'
      path: '/slots'
      fullPath: '/slots/'
      preLoaderRoute: typeof ProtectedSlotsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/schools/': {
      id: '/_protected/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof ProtectedSchoolsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/riders/': {
      id: '/_protected/riders/'
      path: '/riders'
      fullPath: '/riders/'
      preLoaderRoute: typeof ProtectedRidersIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/': {
      id: '/_protected/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ProtectedReportsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/profile/': {
      id: '/_protected/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProtectedProfileIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/preferences/': {
      id: '/_protected/preferences/'
      path: '/preferences'
      fullPath: '/preferences/'
      preLoaderRoute: typeof ProtectedPreferencesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/organizations/': {
      id: '/_protected/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof ProtectedOrganizationsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/income-groups/': {
      id: '/_protected/income-groups/'
      path: '/income-groups'
      fullPath: '/income-groups/'
      preLoaderRoute: typeof ProtectedIncomeGroupsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fiscal-years/': {
      id: '/_protected/fiscal-years/'
      path: '/fiscal-years'
      fullPath: '/fiscal-years/'
      preLoaderRoute: typeof ProtectedFiscalYearsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fees/': {
      id: '/_protected/fees/'
      path: '/fees'
      fullPath: '/fees/'
      preLoaderRoute: typeof ProtectedFeesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fee-heads/': {
      id: '/_protected/fee-heads/'
      path: '/fee-heads'
      fullPath: '/fee-heads/'
      preLoaderRoute: typeof ProtectedFeeHeadsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expenses/': {
      id: '/_protected/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ProtectedExpensesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expense-heads/': {
      id: '/_protected/expense-heads/'
      path: '/expense-heads'
      fullPath: '/expense-heads/'
      preLoaderRoute: typeof ProtectedExpenseHeadsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expense-groups/': {
      id: '/_protected/expense-groups/'
      path: '/expense-groups'
      fullPath: '/expense-groups/'
      preLoaderRoute: typeof ProtectedExpenseGroupsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/credit-notes/': {
      id: '/_protected/credit-notes/'
      path: '/credit-notes'
      fullPath: '/credit-notes/'
      preLoaderRoute: typeof ProtectedCreditNotesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_guest/login/': {
      id: '/_guest/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof GuestLoginIndexRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_protected/reports/vehicle-fee-collection': {
      id: '/_protected/reports/vehicle-fee-collection'
      path: '/reports/vehicle-fee-collection'
      fullPath: '/reports/vehicle-fee-collection'
      preLoaderRoute: typeof ProtectedReportsVehicleFeeCollectionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/school-fee-collection': {
      id: '/_protected/reports/school-fee-collection'
      path: '/reports/school-fee-collection'
      fullPath: '/reports/school-fee-collection'
      preLoaderRoute: typeof ProtectedReportsSchoolFeeCollectionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/rider-fee-collection': {
      id: '/_protected/reports/rider-fee-collection'
      path: '/reports/rider-fee-collection'
      fullPath: '/reports/rider-fee-collection'
      preLoaderRoute: typeof ProtectedReportsRiderFeeCollectionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/pending-collection': {
      id: '/_protected/reports/pending-collection'
      path: '/reports/pending-collection'
      fullPath: '/reports/pending-collection'
      preLoaderRoute: typeof ProtectedReportsPendingCollectionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/monthly-trend': {
      id: '/_protected/reports/monthly-trend'
      path: '/reports/monthly-trend'
      fullPath: '/reports/monthly-trend'
      preLoaderRoute: typeof ProtectedReportsMonthlyTrendRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/income-expense': {
      id: '/_protected/reports/income-expense'
      path: '/reports/income-expense'
      fullPath: '/reports/income-expense'
      preLoaderRoute: typeof ProtectedReportsIncomeExpenseRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/daily-collection': {
      id: '/_protected/reports/daily-collection'
      path: '/reports/daily-collection'
      fullPath: '/reports/daily-collection'
      preLoaderRoute: typeof ProtectedReportsDailyCollectionRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/reports/credit-notes': {
      id: '/_protected/reports/credit-notes'
      path: '/reports/credit-notes'
      fullPath: '/reports/credit-notes'
      preLoaderRoute: typeof ProtectedReportsCreditNotesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fees/new': {
      id: '/_protected/fees/new'
      path: '/fees/new'
      fullPath: '/fees/new'
      preLoaderRoute: typeof ProtectedFeesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expenses/new': {
      id: '/_protected/expenses/new'
      path: '/expenses/new'
      fullPath: '/expenses/new'
      preLoaderRoute: typeof ProtectedExpensesNewRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/fees/$feeId/edit': {
      id: '/_protected/fees/$feeId/edit'
      path: '/fees/$feeId/edit'
      fullPath: '/fees/$feeId/edit'
      preLoaderRoute: typeof ProtectedFeesFeeIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/expenses/$expenseId/edit': {
      id: '/_protected/expenses/$expenseId/edit'
      path: '/expenses/$expenseId/edit'
      fullPath: '/expenses/$expenseId/edit'
      preLoaderRoute: typeof ProtectedExpensesExpenseIdEditRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface GuestRouteChildren {
  GuestLoginIndexRoute: typeof GuestLoginIndexRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginIndexRoute: GuestLoginIndexRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface ProtectedRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedExpensesNewRoute: typeof ProtectedExpensesNewRoute
  ProtectedFeesNewRoute: typeof ProtectedFeesNewRoute
  ProtectedReportsCreditNotesRoute: typeof ProtectedReportsCreditNotesRoute
  ProtectedReportsDailyCollectionRoute: typeof ProtectedReportsDailyCollectionRoute
  ProtectedReportsIncomeExpenseRoute: typeof ProtectedReportsIncomeExpenseRoute
  ProtectedReportsMonthlyTrendRoute: typeof ProtectedReportsMonthlyTrendRoute
  ProtectedReportsPendingCollectionRoute: typeof ProtectedReportsPendingCollectionRoute
  ProtectedReportsRiderFeeCollectionRoute: typeof ProtectedReportsRiderFeeCollectionRoute
  ProtectedReportsSchoolFeeCollectionRoute: typeof ProtectedReportsSchoolFeeCollectionRoute
  ProtectedReportsVehicleFeeCollectionRoute: typeof ProtectedReportsVehicleFeeCollectionRoute
  ProtectedCreditNotesIndexRoute: typeof ProtectedCreditNotesIndexRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
  ProtectedExpenseGroupsIndexRoute: typeof ProtectedExpenseGroupsIndexRoute
  ProtectedExpenseHeadsIndexRoute: typeof ProtectedExpenseHeadsIndexRoute
  ProtectedExpensesIndexRoute: typeof ProtectedExpensesIndexRoute
  ProtectedFeeHeadsIndexRoute: typeof ProtectedFeeHeadsIndexRoute
  ProtectedFeesIndexRoute: typeof ProtectedFeesIndexRoute
  ProtectedFiscalYearsIndexRoute: typeof ProtectedFiscalYearsIndexRoute
  ProtectedIncomeGroupsIndexRoute: typeof ProtectedIncomeGroupsIndexRoute
  ProtectedOrganizationsIndexRoute: typeof ProtectedOrganizationsIndexRoute
  ProtectedPreferencesIndexRoute: typeof ProtectedPreferencesIndexRoute
  ProtectedProfileIndexRoute: typeof ProtectedProfileIndexRoute
  ProtectedReportsIndexRoute: typeof ProtectedReportsIndexRoute
  ProtectedRidersIndexRoute: typeof ProtectedRidersIndexRoute
  ProtectedSchoolsIndexRoute: typeof ProtectedSchoolsIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedSlotsIndexRoute: typeof ProtectedSlotsIndexRoute
  ProtectedUserInitialValuesIndexRoute: typeof ProtectedUserInitialValuesIndexRoute
  ProtectedUserSettingsIndexRoute: typeof ProtectedUserSettingsIndexRoute
  ProtectedUsersIndexRoute: typeof ProtectedUsersIndexRoute
  ProtectedVehicleTypesIndexRoute: typeof ProtectedVehicleTypesIndexRoute
  ProtectedVehiclesIndexRoute: typeof ProtectedVehiclesIndexRoute
  ProtectedExpensesExpenseIdEditRoute: typeof ProtectedExpensesExpenseIdEditRoute
  ProtectedFeesFeeIdEditRoute: typeof ProtectedFeesFeeIdEditRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedExpensesNewRoute: ProtectedExpensesNewRoute,
  ProtectedFeesNewRoute: ProtectedFeesNewRoute,
  ProtectedReportsCreditNotesRoute: ProtectedReportsCreditNotesRoute,
  ProtectedReportsDailyCollectionRoute: ProtectedReportsDailyCollectionRoute,
  ProtectedReportsIncomeExpenseRoute: ProtectedReportsIncomeExpenseRoute,
  ProtectedReportsMonthlyTrendRoute: ProtectedReportsMonthlyTrendRoute,
  ProtectedReportsPendingCollectionRoute:
    ProtectedReportsPendingCollectionRoute,
  ProtectedReportsRiderFeeCollectionRoute:
    ProtectedReportsRiderFeeCollectionRoute,
  ProtectedReportsSchoolFeeCollectionRoute:
    ProtectedReportsSchoolFeeCollectionRoute,
  ProtectedReportsVehicleFeeCollectionRoute:
    ProtectedReportsVehicleFeeCollectionRoute,
  ProtectedCreditNotesIndexRoute: ProtectedCreditNotesIndexRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
  ProtectedExpenseGroupsIndexRoute: ProtectedExpenseGroupsIndexRoute,
  ProtectedExpenseHeadsIndexRoute: ProtectedExpenseHeadsIndexRoute,
  ProtectedExpensesIndexRoute: ProtectedExpensesIndexRoute,
  ProtectedFeeHeadsIndexRoute: ProtectedFeeHeadsIndexRoute,
  ProtectedFeesIndexRoute: ProtectedFeesIndexRoute,
  ProtectedFiscalYearsIndexRoute: ProtectedFiscalYearsIndexRoute,
  ProtectedIncomeGroupsIndexRoute: ProtectedIncomeGroupsIndexRoute,
  ProtectedOrganizationsIndexRoute: ProtectedOrganizationsIndexRoute,
  ProtectedPreferencesIndexRoute: ProtectedPreferencesIndexRoute,
  ProtectedProfileIndexRoute: ProtectedProfileIndexRoute,
  ProtectedReportsIndexRoute: ProtectedReportsIndexRoute,
  ProtectedRidersIndexRoute: ProtectedRidersIndexRoute,
  ProtectedSchoolsIndexRoute: ProtectedSchoolsIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedSlotsIndexRoute: ProtectedSlotsIndexRoute,
  ProtectedUserInitialValuesIndexRoute: ProtectedUserInitialValuesIndexRoute,
  ProtectedUserSettingsIndexRoute: ProtectedUserSettingsIndexRoute,
  ProtectedUsersIndexRoute: ProtectedUsersIndexRoute,
  ProtectedVehicleTypesIndexRoute: ProtectedVehicleTypesIndexRoute,
  ProtectedVehiclesIndexRoute: ProtectedVehiclesIndexRoute,
  ProtectedExpensesExpenseIdEditRoute: ProtectedExpensesExpenseIdEditRoute,
  ProtectedFeesFeeIdEditRoute: ProtectedFeesFeeIdEditRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  GuestRoute: GuestRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
